function buildGradeWords(firstNouns, secondNouns, firstVerbs, secondVerbs) {
  const seen = new Set();
  return [firstNouns, secondNouns, firstVerbs, secondVerbs]
    .flat()
    .reduce((words, [latin, english, emoji = '']) => {
      const key = `${latin.toLowerCase()}|${english.toLowerCase()}`;
      if (seen.has(key)) return words;
      seen.add(key);
      words.push({ latin, english, emoji });
      return words;
    }, []);
}

const GRADE_WORDS = {
  3: buildGradeWords(
    [
      ['puella', 'girl', '👧'],
      ['femina', 'woman', '👩'],
      ['terra', 'earth', '🌎'],
      ['insula', 'island', '🏝️'],
      ['via', 'road / way', '🛣️'],
      ['casa', 'house / home', '🏡'],
      ['mensa', 'table', '🍽️'],
      ['cathedra', 'chair', '🪑'],
      ['porta', 'gate', '🚪'],
      ['penna', 'feather', '🪶'],
      ['aqua', 'water', '💧'],
      ['cena', 'dinner', '🍲'],
      ['hora', 'hour', '⏰'],
      ['rosa', 'rose', '🌹'],
      ['silva', 'forest', '🌲'],
      ['turba', 'crowd', '👥'],
      ['familia', 'family', '👨‍👩‍👧‍👦'],
      ['villa', 'country house', '🏡'],
      ['rota', 'wheel', '🛞'],
      ['epistula', 'letter', '✉️'],
      ['stella', 'star', '⭐'],
      ['luna', 'moon', '🌙'],
      ['corona', 'crown', '👑'],
      ['unda', 'wave', '🌊'],
      ['fenestra', 'window', '🪟'],
      ['aula', 'hall', '🏛️'],
      ['cultura', 'culture', '🎭'],
      ['filia', 'daughter', '👧'],
      ['matrona', 'matron', '👵'],
      ['schola', 'school', '🏫'],
      ['vitta', 'ribbon', '🎀'],
      ['navicula', 'small ship', '⛵'],
      ['sagitta', 'arrow', '🏹'],
      ['taberna', 'shop', '🏪'],
      ['raeda', 'carriage', '🚗'],
      ['fabula', 'story', '📖'],
      ['columna', 'column', '🏛️'],
      ['ala', 'wing', '🪽']
    ],
    [
      ['puer', 'boy', '👦'],
      ['equus', 'horse', '🐎'],
      ['liber', 'book', '📚'],
      ['magister', 'teacher', '👩‍🏫'],
      ['servus', 'servant', '🧑‍🍳'],
      ['dominus', 'master', '🧔'],
      ['filius', 'son', '👦'],
      ['annus', 'year', '📅'],
      ['hortus', 'garden', '🌿'],
      ['gladius', 'sword', '🗡️'],
      ['cibus', 'food', '🍎'],
      ['signum', 'sign', '⚠️'],
      ['bellum', 'war', '⚔️'],
      ['donum', 'gift', '🎁'],
      ['oppidum', 'town', '🏘️'],
      ['ager', 'field', '🌾'],
      ['poeta', 'poet', '🧑‍🎤'],
      ['nuntius', 'messenger', '📨'],
      ['socius', 'friend', '🤝'],
      ['amicus', 'friend', '🙂'],
      ['aurum', 'gold', '🥇'],
      ['oculus', 'eye', '👁️'],
      ['circulus', 'circle', '⭕'],
      ['humus', 'earth', '🌱'],
      ['loculus', 'small place', '📦'],
      ['murus', 'wall', '🧱'],
      ['numerus', 'number', '🔢'],
      ['senatus', 'senate', '🏛️'],
      ['equitet', 'cavalryman', '🐴'],
      ['pulcher', 'beautiful', '' ],
      ['libellus', 'little book', '📘'],
      ['arcus', 'arch', '🌈'],
      ['cubiculum', 'bedroom', '🛌'],
      ['motus', 'motion', '💨'],
      ['librarius', 'bookseller', '📚'],
      ['sumptus', 'expense', '💰'],
      ['sacerdos', 'priest', '⛪'],
      ['vir', 'man', '👨']
    ],
    [
      ['amo', 'love', '❤️'],
      ['voco', 'call', '📞'],
      ['porto', 'carry', '🎒'],
      ['narro', 'tell', '🗣️'],
      ['canto', 'sing', '🎶'],
      ['laboro', 'work', '💼'],
      ['laudo', 'praise', '👏'],
      ['rogo', 'ask', '❓'],
      ['specto', 'watch', '👀'],
      ['curo', 'care for', '🩺'],
      ['servo', 'save', '💾'],
      ['amo', 'love', '❤️'],
      ['saluto', 'greet', '👋'],
      ['dono', 'give', '🎁'],
      ['monstro', 'show', '🖼️'],
      ['navigo', 'sail', '⛵'],
      ['appello', 'name', '🧾'],
      ['festo', 'celebrate', '🎉'],
      ['paro', 'prepare', '🔧'],
      ['tento', 'try', '✊']
    ],
    [
      ['habeo', 'have', '🤲'],
      ['video', 'see', '👀'],
      ['teneo', 'hold', '✋'],
      ['moneo', 'warn', '⚠️'],
      ['doceo', 'teach', '👩‍🏫'],
      ['maneo', 'remain', '🏠'],
      ['moveo', 'move', '🏃'],
      ['timeo', 'fear', '😨'],
      ['respondeo', 'answer', '✅'],
      ['curro', 'run', '🏃'],
      ['ambulo', 'walk', '🚶'],
      ['rideo', 'laugh', '😂'],
      ['gaudeo', 'rejoice', '😊'],
      ['video', 'see', '👁️'],
      ['salveo', 'greet', '👋'],
      ['jubeo', 'order', '🗣️'],
      ['timeo', 'fear', '😱'],
      ['ordeo', 'order', '📝'],
      ['sedeo', 'sit', '🪑'],
      ['moveo', 'move', '📦']
    ]
  ),
  4: buildGradeWords(
    [
      ['patria', 'homeland', '🏞️'],
      ['civitas', 'city', '🏛️'],
      ['via', 'way', '🛣️'],
      ['arma', 'arms', '⚔️'],
      ['lumen', 'light', '💡'],
      ['aetas', 'age', '⏳'],
      ['mensa', 'table', '🍽️'],
      ['scriba', 'scribe', '✍️'],
      ['aurora', 'dawn', '🌅'],
      ['victoria', 'victory', '🏆'],
      ['porta', 'door', '🚪'],
      ['cultura', 'culture', '🎭'],
      ['poeta', 'poet', '🎤'],
      ['natura', 'nature', '🌿'],
      ['carmina', 'songs', '🎵'],
      ['tempestas', 'storm', '⛈️'],
      ['medicina', 'medicine', '💊'],
      ['theatrum', 'theater', '🎭'],
      ['sapientia', 'wisdom', '🧠'],
      ['tristitia', 'sadness', '😢'],
      ['amor', 'love', '❤️'],
      ['timor', 'fear', '😨'],
      ['ecclesia', 'church', '⛪'],
      ['aurum', 'gold', '🥇'],
      ['flumen', 'river', '🏞️'],
      ['lucerna', 'lamp', '🪔'],
      ['arma', 'weapons', '🛡️'],
      ['regina', 'queen', '👑'],
      ['virgo', 'maiden', '👧'],
      ['tempus', 'time', '⏰'],
      ['virtus', 'virtue', '✨'],
      ['sapientia', 'wisdom', '📘'],
      ['natura', 'nature', '🌳'],
      ['silva', 'forest', '🌲'],
      ['aurora', 'dawn', '🌅'],
      ['musica', 'music', '🎵'],
      ['poema', 'poem', '📜'],
      ['fabula', 'story', '📖'],
      ['salus', 'health', '🩺']
    ],
    [
      ['amicus', 'friend', '🤝'],
      ['consul', 'consul', '👔'],
      ['senex', 'old man', '👴'],
      ['iuvenis', 'young person', '🧑'],
      ['imperator', 'commander', '🪖'],
      ['dux', 'leader', '👨‍✈️'],
      ['legatus', 'envoy', '📨'],
      ['equus', 'horse', '🐎'],
      ['navis', 'ship', '🚢'],
      ['oppidum', 'town', '🏘️'],
      ['donum', 'gift', '🎁'],
      ['bellum', 'war', '⚔️'],
      ['agricola', 'farmer', '🚜'],
      ['mercator', 'merchant', '💼'],
      ['insula', 'island', '🏝️'],
      ['mundus', 'world', '🌍'],
      ['templum', 'temple', '⛪'],
      ['hortus', 'garden', '🌺'],
      ['pomerium', 'boundary', '📏'],
      ['opulentia', 'wealth', '💰'],
      ['aurum', 'gold', '🥇'],
      ['argentum', 'silver', '🥈'],
      ['vinum', 'wine', '🍷'],
      ['panis', 'bread', '🍞'],
      ['iocus', 'joke', '😂'],
      ['memoria', 'memory', '🧠'],
      ['notitia', 'information', '📚'],
      ['pictura', 'picture', '🖼️'],
      ['professio', 'profession', '💼'],
      ['cursus', 'course', '🏃'],
      ['praemium', 'reward', '🏅'],
      ['nocturnus', 'nightly', '🌙'],
      ['diurnus', 'daily', '☀️'],
      ['victoria', 'victory', '🏆'],
      ['tempestas', 'weather', '☁️'],
      ['sophia', 'wisdom', '🧠'],
      ['disciplina', 'training', '🎓'],
      ['educatio', 'education', '📖'],
      ['filius', 'son', '👦']
    ],
    [
      ['amo', 'love', '❤️'],
      ['doceo', 'teach', '👩‍🏫'],
      ['rogo', 'ask', '❓'],
      ['porto', 'carry', '🎒'],
      ['navigo', 'sail', '⛵'],
      ['specto', 'watch', '👀'],
      ['saluto', 'greet', '👋'],
      ['curo', 'care', '🩺'],
      ['laudo', 'praise', '👏'],
      ['paro', 'prepare', '🛠️'],
      ['canto', 'sing', '🎤'],
      ['festo', 'celebrate', '🎉'],
      ['voco', 'call', '📞'],
      ['visito', 'visit', '🏠'],
      ['spero', 'hope', '🤞'],
      ['servio', 'serve', '🤲'],
      ['rogito', 'ask repeatedly', '❓'],
      ['narro', 'tell', '🗣️'],
      ['porto', 'carry', '📦'],
      ['ambulo', 'walk', '🚶']
    ],
    [
      ['video', 'see', '👁️'],
      ['habeo', 'have', '🤲'],
      ['teneo', 'hold', '✋'],
      ['moveo', 'move', '🚚'],
      ['maneo', 'remain', '🏠'],
      ['doceo', 'teach', '📚'],
      ['respondeo', 'answer', '✅'],
      ['timeo', 'fear', '😱'],
      ['gaudeo', 'rejoice', '😄'],
      ['iubeo', 'order', '🗣️'],
      ['sedeo', 'sit', '🪑'],
      ['video', 'see', '👀'],
      ['moneo', 'warn', '⚠️'],
      ['moveo', 'move', '🏃'],
      ['spondeo', 'promise', '🤝'],
      ['pondeo', 'weigh', '⚖️'],
      ['sileo', 'be silent', '🤫'],
      ['suscenseo', 'be angry', '😠'],
      ['video', 'see', '👀'],
      ['timeo', 'fear', '😨']
    ]
  ),
  5: buildGradeWords(
    [
      ['adventus', 'arrival', '🚪'],
      ['clavis', 'key', '🗝️'],
      ['digitorum', 'finger', '🖐️'],
      ['epistula', 'letter', '✉️'],
      ['fabrica', 'workshop', '🏭'],
      ['gymnasium', 'gym', '🏟️'],
      ['horologium', 'clock', '⏰'],
      ['instrumentum', 'instrument', '🎸'],
      ['ludus', 'play', '🎮'],
      ['magisterium', 'mastery', '🎓'],
      ['necto', 'to bind', '🔗'],
      ['opus', 'work', '🏗️'],
      ['porta', 'gate', '🚪'],
      ['quaestio', 'question', '❓'],
      ['respublica', 'republic', '🏛️'],
      ['scientia', 'knowledge', '🧠'],
      ['theatrum', 'theater', '🎭'],
      ['ultima', 'last', '🔚'],
      ['via', 'road', '🛣️'],
      ['voluptas', 'pleasure', '😄'],
      ['audacia', 'boldness', '💪'],
      ['bona', 'goods', '🛍️'],
      ['calamus', 'reed', '✒️'],
      ['decor', 'beauty', '💐'],
      ['exemplum', 'example', '📘'],
      ['feriae', 'holidays', '🎉'],
      ['gloria', 'glory', '🏅'],
      ['hyacinthus', 'hyacinth', '🌸'],
      ['insula', 'island', '🏝️'],
      ['judicium', 'judgment', '⚖️'],
      ['kalendarum', 'calendar', '📅'],
      ['lex', 'law', '📜'],
      ['mundus', 'world', '🌎'],
      ['natura', 'nature', '🌿'],
      ['officium', 'duty', '🛡️'],
      ['praemium', 'reward', '🏆'],
      ['quaestio', 'question', '❓'],
      ['regnum', 'kingdom', '👑']
    ],
    [
      ['aurum', 'gold', '🥇'],
      ['bellum', 'war', '⚔️'],
      ['civis', 'citizen', '🧑‍🤝‍🧑'],
      ['dies', 'day', '☀️'],
      ['equus', 'horse', '🐎'],
      ['flos', 'flower', '🌸'],
      ['gaudium', 'joy', '😄'],
      ['homo', 'person', '🧍'],
      ['ignis', 'fire', '🔥'],
      ['iocus', 'joke', '😂'],
      ['jus', 'law', '⚖️'],
      ['lex', 'law', '📜'],
      ['miles', 'soldier', '🪖'],
      ['navis', 'ship', '🚢'],
      ['opus', 'work', '⚒️'],
      ['pater', 'father', '👨'],
      ['regnum', 'kingdom', '🏰'],
      ['senex', 'old man', '👴'],
      ['tempus', 'time', '⏱️'],
      ['verbum', 'word', '📝'],
      ['vir', 'man', '👨'],
      ['virtus', 'virtue', '✨'],
      ['vulnus', 'wound', '🩸'],
      ['zenithus', 'zenith', '☀️'],
      ['agricola', 'farmer', '🚜'],
      ['barba', 'beard', '🧔'],
      ['cultura', 'culture', '🎨'],
      ['deus', 'god', '🙏'],
      ['equites', 'knights', '🐴'],
      ['fides', 'faith', '✝️'],
      ['gloria', 'glory', '🏅'],
      ['honos', 'honor', '🏛️'],
      ['insula', 'island', '🏝️'],
      ['jocus', 'joke', '😂'],
      ['lega', 'ambassador', '🕊️'],
      ['mensa', 'table', '🍽️'],
      ['noster', 'our', '👥'],
      ['opus', 'work', '🛠️']
    ],
    [
      ['amo', 'love', '❤️'],
      ['video', 'see', '👀'],
      ['doceo', 'teach', '📚'],
      ['cupio', 'desire', '✨'],
      ['amo', 'love', '💛'],
      ['laudo', 'praise', '👏'],
      ['porto', 'carry', '🎒'],
      ['narro', 'tell', '🗣️'],
      ['rego', 'rule', '👑'],
      ['servo', 'save', '💾'],
      ['voco', 'call', '📞'],
      ['rogo', 'ask', '❓'],
      ['facio', 'make', '🛠️'],
      ['scribo', 'write', '✍️'],
      ['lego', 'read', '📖'],
      ['amo', 'love', '❤️'],
      ['curro', 'run', '🏃'],
      ['audio', 'hear', '👂'],
      ['dormio', 'sleep', '😴'],
      ['pugno', 'fight', '⚔️']
    ],
    [
      ['habeo', 'have', '🤲'],
      ['video', 'see', '👀'],
      ['teneo', 'hold', '✋'],
      ['doceo', 'teach', '👨‍🏫'],
      ['maneo', 'remain', '🏠'],
      ['moveo', 'move', '🚚'],
      ['respondeo', 'answer', '✅'],
      ['timeo', 'fear', '😨'],
      ['gaudeo', 'rejoice', '😁'],
      ['sedeo', 'sit', '🪑'],
      ['video', 'see', '👁️'],
      ['moneo', 'warn', '⚠️'],
      ['doceo', 'teach', '📘'],
      ['moveo', 'move', '🏃'],
      ['studeo', 'study', '📖'],
      ['iubeo', 'order', '📝'],
      ['sileo', 'be silent', '🤫'],
      ['spondeo', 'promise', '🤝'],
      ['soleo', 'am accustomed', '🔁'],
      ['video', 'see', '👀']
    ]
  ),
  6: buildGradeWords(
    [
      ['schola', 'school', '🏫'],
      ['ludus', 'game', '🎮'],
      ['magister', 'teacher', '👩‍🏫'],
      ['discipula', 'student', '🧑‍🎓'],
      ['liber', 'book', '📚'],
      ['codex', 'book', '📘'],
      ['lectus', 'couch', '🛋️'],
      ['scrinium', 'box', '📦'],
      ['calamus', 'pen', '✒️'],
      ['tabula', 'tablet', '🪵'],
      ['aula', 'hall', '🏛️'],
      ['cella', 'room', '🏠'],
      ['vestis', 'clothing', '👕'],
      ['toga', 'toga', '👘'],
      ['pelvis', 'pool', '🏊'],
      ['piscina', 'pool', '🏊'],
      ['sepulchrum', 'tomb', '⚰️'],
      ['tempestas', 'storm', '⛈️'],
      ['aurora', 'dawn', '🌅'],
      ['noctua', 'owl', '🦉'],
      ['luna', 'moon', '🌙'],
      ['sol', 'sun', '☀️'],
      ['caelum', 'sky', '🌌'],
      ['tempus', 'time', '⏱️'],
      ['horn', 'horn', '📯'],
      ['tintinnabulum', 'bell', '🔔'],
      ['equa', 'mare', '🌊'],
      ['species', 'appearance', '👁️'],
      ['natura', 'nature', '🌲'],
      ['astrum', 'star', '🌟'],
      ['mysterium', 'mystery', '🕵️'],
      ['vis', 'force', '💪'],
      ['ars', 'art', '🎨'],
      ['ingenium', 'talent', '💡'],
      ['memor', 'mindful', '🧠'],
      ['pax', 'peace', '🕊️'],
      ['tempestas', 'weather', '☁️']
    ],
    [
      ['agricola', 'farmer', '🚜'],
      ['que', 'and', '➕'],
      ['mercator', 'merchant', '💼'],
      ['civis', 'citizen', '🧑‍🤝‍🧑'],
      ['senator', 'senator', '🏛️'],
      ['senex', 'old man', '👴'],
      ['iuvenis', 'young person', '🧑'],
      ['nuntius', 'messenger', '📨'],
      ['legatus', 'envoy', '🤝'],
      ['gladius', 'sword', '🗡️'],
      ['pugio', 'dagger', '🗡️'],
      ['cloaca', 'sewer', '🚰'],
      ['fossa', 'ditch', '🕳️'],
      ['insula', 'island', '🏝️'],
      ['oppidum', 'town', '🏠'],
      ['bellum', 'war', '⚔️'],
      ['forum', 'marketplace', '🏛️'],
      ['amphitheatrum', 'amphitheater', '🎭'],
      ['bibliotheca', 'library', '📚'],
      ['domus', 'house', '🏡'],
      ['fluvius', 'river', '🏞️'],
      ['mons', 'mountain', '⛰️'],
      ['silva', 'forest', '🌳'],
      ['vicus', 'village', '🏘️'],
      ['feriae', 'holidays', '🎉'],
      ['gladius', 'sword', '🛡️'],
      ['hortus', 'garden', '🌺'],
      ['ludus', 'school', '🏫'],
      ['martialis', 'martial', '🥋'],
      ['natura', 'nature', '🌿'],
      ['pastor', 'shepherd', '🐑'],
      ['regina', 'queen', '👸'],
      ['rex', 'king', '🤴'],
      ['scriba', 'scribe', '✍️'],
      ['templum', 'temple', '⛪'],
      ['umbras', 'ghost', '👻'],
      ['vesper', 'evening', '🌆'],
      ['zenith', 'zenith', '☀️']
    ],
    [
      ['amo', 'love', '❤️'],
      ['video', 'see', '👁️'],
      ['scribo', 'write', '✍️'],
      ['lego', 'read', '📖'],
      ['audio', 'hear', '👂'],
      ['curro', 'run', '🏃'],
      ['ambulo', 'walk', '🚶'],
      ['porto', 'carry', '🎒'],
      ['navigo', 'sail', '⛵'],
      ['dormio', 'sleep', '😴'],
      ['laudo', 'praise', '👏'],
      ['facio', 'make', '🛠️'],
      ['amo', 'love', '❤️'],
      ['spero', 'hope', '🤞'],
      ['lego', 'read', '📚'],
      ['scribo', 'write', '📝'],
      ['cogito', 'think', '💭'],
      ['mitto', 'send', '✉️'],
      ['venio', 'come', '🚶'],
      ['dico', 'say', '🗣️']
    ],
    [
      ['habeo', 'have', '🤲'],
      ['video', 'see', '👀'],
      ['teneo', 'hold', '✋'],
      ['maneo', 'remain', '🏠'],
      ['doceo', 'teach', '👨‍🏫'],
      ['moveo', 'move', '🚚'],
      ['respondeo', 'answer', '✅'],
      ['timeo', 'fear', '😨'],
      ['gaudeo', 'rejoice', '😁'],
      ['iubeo', 'order', '📝'],
      ['sedeo', 'sit', '🪑'],
      ['video', 'see', '👁️'],
      ['moneo', 'warn', '⚠️'],
      ['doceo', 'teach', '📘'],
      ['moveo', 'move', '🏃'],
      ['studeo', 'study', '📖'],
      ['ostendo', 'show', '🖼️'],
      ['sileo', 'be silent', '🤫'],
      ['soleo', 'am accustomed', '🔁'],
      ['gaudeo', 'rejoice', '😄']
    ]
  ),
  7: buildGradeWords(
    [
      ['adulescens', 'young person', '🧑'],
      ['bellum', 'war', '⚔️'],
      ['capillus', 'hair', '💇'],
      ['dux', 'leader', '👨‍✈️'],
      ['exercitus', 'army', '🪖'],
      ['fabrica', 'workshop', '🏭'],
      ['gaudium', 'joy', '😄'],
      ['harena', 'sand', '🏖️'],
      ['insula', 'island', '🏝️'],
      ['iustitia', 'justice', '⚖️'],
      ['jumentum', 'beast of burden', '🐂'],
      ['legio', 'legion', '🪖'],
      ['maritus', 'husband', '👨‍🦱'],
      ['natura', 'nature', '🌿'],
      ['opera', 'works', '🛠️'],
      ['poeta', 'poet', '🧑‍🎤'],
      ['quaestor', 'financial officer', '💰'],
      ['regnum', 'kingdom', '👑'],
      ['senatus', 'senate', '🏛️'],
      ['temporis', 'time', '⏱️'],
      ['urbis', 'city', '🏙️'],
      ['victoria', 'victory', '🏆'],
      ['versus', 'line of poetry', '📜'],
      ['vulnus', 'wound', '🩸'],
      ['aestas', 'summer', '🌞'],
      ['hiems', 'winter', '❄️'],
      ['autumnus', 'autumn', '🍂'],
      ['ver', 'spring', '🌸'],
      ['tempestas', 'storm', '⛈️'],
      ['caelum', 'sky', '☁️'],
      ['aurora', 'dawn', '🌅'],
      ['crepitus', 'noise', '🔊'],
      ['domus', 'home', '🏡'],
      ['fides', 'faith', '✝️'],
      ['habitus', 'appearance', '👕'],
      ['ignis', 'fire', '🔥'],
      ['lumen', 'light', '💡'],
      ['mortuus', 'dead', '💀'],
      ['nox', 'night', '🌙']
    ],
    [
      ['amicus', 'friend', '🤝'],
      ['civis', 'citizen', '👥'],
      ['consul', 'consul', '🧑‍⚖️'],
      ['legatus', 'envoy', '🕊️'],
      ['magister', 'teacher', '👨‍🏫'],
      ['milites', 'soldiers', '🪖'],
      ['navis', 'ship', '🚢'],
      ['oppidum', 'town', '🏘️'],
      ['pastor', 'shepherd', '🐑'],
      ['poeta', 'poet', '🧑‍🎤'],
      ['rex', 'king', '🤴'],
      ['regina', 'queen', '👸'],
      ['senex', 'old man', '👴'],
      ['servus', 'slave', '🧑‍🤝‍🧑'],
      ['sternua', 'sneeze', '😤'],
      ['turba', 'crowd', '👥'],
      ['urbs', 'city', '🏙️'],
      ['victor', 'winner', '🏆'],
      ['vir', 'man', '👨'],
      ['virgo', 'maiden', '👧'],
      ['aqua', 'water', '💧'],
      ['cibus', 'food', '🍎'],
      ['donum', 'gift', '🎁'],
      ['forum', 'marketplace', '🏛️'],
      ['gladius', 'sword', '🗡️'],
      ['hortus', 'garden', '🌺'],
      ['iter', 'journey', '🧭'],
      ['murmur', 'murmur', '🗯️'],
      ['pugna', 'battle', '⚔️'],
      ['spes', 'hope', '✨'],
      ['tempus', 'time', '⏰'],
      ['umbra', 'shadow', '🌫️'],
      ['via', 'road', '🛣️'],
      ['vox', 'voice', '🗣️'],
      ['scripta', 'writing', '✍️'],
      ['membra', 'limbs', '🦵'],
      ['barba', 'beard', '🧔'],
      ['caput', 'head', '🧠']
    ],
    [
      ['amo', 'love', '❤️'],
      ['video', 'see', '👁️'],
      ['scribo', 'write', '✍️'],
      ['lego', 'read', '📖'],
      ['audio', 'hear', '👂'],
      ['curro', 'run', '🏃'],
      ['ambulo', 'walk', '🚶'],
      ['porto', 'carry', '🎒'],
      ['navigo', 'sail', '⛵'],
      ['dormio', 'sleep', '😴'],
      ['laudo', 'praise', '👏'],
      ['facio', 'make', '🛠️'],
      ['amo', 'love', '❤️'],
      ['spero', 'hope', '🤞'],
      ['rego', 'rule', '👑'],
      ['dico', 'say', '🗣️'],
      ['pono', 'place', '📍'],
      ['traho', 'pull', '🧲'],
      ['venio', 'come', '🚶'],
      ['porto', 'carry', '📦']
    ],
    [
      ['habeo', 'have', '🤲'],
      ['video', 'see', '👀'],
      ['teneo', 'hold', '✋'],
      ['maneo', 'remain', '🏠'],
      ['doceo', 'teach', '📚'],
      ['moveo', 'move', '🏃'],
      ['respondeo', 'answer', '✅'],
      ['timeo', 'fear', '😨'],
      ['gaudeo', 'rejoice', '😁'],
      ['iubeo', 'order', '📝'],
      ['sedeo', 'sit', '🪑'],
      ['video', 'see', '👁️'],
      ['moneo', 'warn', '⚠️'],
      ['doceo', 'teach', '📘'],
      ['moveo', 'move', '🚚'],
      ['studeo', 'study', '📖'],
      ['ostendo', 'show', '🖼️'],
      ['sileo', 'be silent', '🤫'],
      ['soleo', 'am accustomed', '🔁'],
      ['gaudeo', 'rejoice', '😄']
    ]
  ),
  8: buildGradeWords(
    [
      ['aurora', 'dawn', '🌅'],
      ['bellum', 'war', '⚔️'],
      ['clerus', 'clergy', '⛪'],
      ['decor', 'beauty', '💐'],
      ['equitas', 'fairness', '⚖️'],
      ['flora', 'plants', '🌿'],
      ['gloria', 'glory', '🏆'],
      ['honor', 'honor', '🏅'],
      ['ingenium', 'talent', '💡'],
      ['judicium', 'judgment', '⚖️'],
      ['lex', 'law', '📜'],
      ['magnitudo', 'size', '📏'],
      ['natura', 'nature', '🌳'],
      ['opus', 'work', '🛠️'],
      ['punctum', 'point', '📌'],
      ['quaestio', 'question', '❓'],
      ['res', 'thing', '🧩'],
      ['sententia', 'opinion', '💬'],
      ['tempus', 'time', '⏳'],
      ['uranus', 'sky', '☁️'],
      ['virtus', 'virtue', '✨'],
      ['voluptas', 'pleasure', '😄'],
      ['zephyrus', 'west wind', '🌬️'],
      ['aestus', 'tide', '🌊'],
      ['cultura', 'culture', '🎨'],
      ['doctrina', 'teaching', '📚'],
      ['epistula', 'letter', '✉️'],
      ['fabrica', 'workshop', '🏭'],
      ['gradus', 'step', '🪜'],
      ['honestas', 'honesty', '🤝'],
      ['idea', 'idea', '💡'],
      ['judex', 'judge', '👩‍⚖️'],
      ['lex', 'law', '⚖️'],
      ['multitudo', 'crowd', '👥'],
      ['nobilis', 'noble', '👑'],
      ['ordo', 'order', '📋'],
      ['potentia', 'power', '⚡'],
      ['ratio', 'reason', '🧠'],
      ['sapiens', 'wise person', '🧙'],
      ['tempestas', 'storm', '⛈️']
    ],
    [
      ['civis', 'citizen', '👥'],
      ['consul', 'consul', '🧑‍⚖️'],
      ['dux', 'leader', '👨‍✈️'],
      ['exercitus', 'army', '🪖'],
      ['fides', 'faith', '✝️'],
      ['gaudium', 'joy', '😄'],
      ['hostis', 'enemy', '🪓'],
      ['iustitia', 'justice', '⚖️'],
      ['legatus', 'envoy', '📨'],
      ['miles', 'soldier', '🪖'],
      ['nuntius', 'messenger', '📨'],
      ['oppidum', 'town', '🏘️'],
      ['pactum', 'agreement', '🤝'],
      ['quaestor', 'treasurer', '💰'],
      ['rex', 'king', '👑'],
      ['regina', 'queen', '👸'],
      ['senatus', 'senate', '🏛️'],
      ['templum', 'temple', '⛪'],
      ['urbs', 'city', '🏙️'],
      ['victor', 'victor', '🏆'],
      ['virtus', 'virtue', '✨'],
      ['vulnus', 'wound', '🩸'],
      ['aqua', 'water', '💧'],
      ['fortuna', 'fortune', '🍀'],
      ['gratia', 'thanks', '🙏'],
      ['honor', 'honor', '🏅'],
      ['insula', 'island', '🏝️'],
      ['jugum', 'yoke', '🔗'],
      ['lacrima', 'tear', '😢'],
      ['munus', 'gift', '🎁'],
      ['natura', 'nature', '🌿'],
      ['occidens', 'west', '🌅'],
      ['pectus', 'chest', '🫀'],
      ['quaerens', 'seeker', '🔎'],
      ['ratio', 'reason', '🧠'],
      ['sapiens', 'wise one', '🧙'],
      ['tempestas', 'weather', '☁️'],
      ['veritas', 'truth', '✔️']
    ],
    [
      ['amo', 'love', '❤️'],
      ['video', 'see', '👁️'],
      ['scribo', 'write', '✍️'],
      ['lego', 'read', '📖'],
      ['audio', 'hear', '👂'],
      ['curro', 'run', '🏃'],
      ['ambulo', 'walk', '🚶'],
      ['porto', 'carry', '🎒'],
      ['navigo', 'sail', '⛵'],
      ['dormio', 'sleep', '😴'],
      ['laudo', 'praise', '👏'],
      ['facio', 'make', '🛠️'],
      ['spero', 'hope', '🤞'],
      ['rego', 'rule', '👑'],
      ['dico', 'say', '🗣️'],
      ['pono', 'place', '📍'],
      ['traho', 'pull', '🧲'],
      ['venio', 'come', '🚶'],
      ['porto', 'carry', '📦'],
      ['ludo', 'play', '🎮']
    ],
    [
      ['habeo', 'have', '🤲'],
      ['video', 'see', '👀'],
      ['teneo', 'hold', '✋'],
      ['maneo', 'remain', '🏠'],
      ['doceo', 'teach', '📚'],
      ['moveo', 'move', '🏃'],
      ['respondeo', 'answer', '✅'],
      ['timeo', 'fear', '😨'],
      ['gaudeo', 'rejoice', '😁'],
      ['iubeo', 'order', '📝'],
      ['sedeo', 'sit', '🪑'],
      ['video', 'see', '👁️'],
      ['moneo', 'warn', '⚠️'],
      ['doceo', 'teach', '📘'],
      ['moveo', 'move', '🏃'],
      ['studeo', 'study', '📖'],
      ['ostendo', 'show', '🖼️'],
      ['sileo', 'be silent', '🤫'],
      ['soleo', 'am accustomed', '🔁'],
      ['gaudeo', 'rejoice', '😄']
    ]
  )
};

// Curated additions from ref/IMG_2472.jpeg and ref/IMG_2483.jpeg-IMG_2490.jpeg.
// A headword is added only if it does not already occur anywhere in the grade banks.
const REFERENCE_VOCABULARY_BY_GRADE = {
  3: [
    { latin: 'nomen', english: 'name', emoji: '🏷️' },
    { latin: 'discipulus', english: 'student', emoji: '🧑‍🎓' },
    { latin: 'magistra', english: 'female teacher', emoji: '👩‍🏫' },
    { latin: 'tabella', english: 'writing tablet', emoji: '📋' },
    { latin: 'sella', english: 'seat', emoji: '🪑' },
    { latin: 'ianua', english: 'door', emoji: '🚪' },
    { latin: 'folium', english: 'leaf / sheet of paper', emoji: '📄' },
    { latin: 'culpa', english: 'fault / blame', emoji: '🙋' }
  ],
  4: [
    { latin: 'campus', english: 'field / plain', emoji: '🌾' },
    { latin: 'collis', english: 'hill', emoji: '⛰️' },
    { latin: 'mare', english: 'sea', emoji: '🌊' },
    { latin: 'ventus', english: 'wind', emoji: '💨' },
    { latin: 'saxum', english: 'rock', emoji: '🪨' },
    { latin: 'frater', english: 'brother', emoji: '👦' },
    { latin: 'soror', english: 'sister', emoji: '👧' },
    { latin: 'mater', english: 'mother', emoji: '👩' },
    { latin: 'nauta', english: 'sailor', emoji: '⛵' }
  ],
  5: [
    { latin: 'provincia', english: 'province', emoji: '🗺️' },
    { latin: 'portus', english: 'harbor', emoji: '⚓' },
    { latin: 'pons', english: 'bridge', emoji: '🌉' },
    { latin: 'vallum', english: 'wall / rampart', emoji: '🧱' },
    { latin: 'scutum', english: 'shield', emoji: '🛡️' },
    { latin: 'piscator', english: 'fisherman', emoji: '🎣' },
    { latin: 'orator', english: 'speaker / orator', emoji: '🗣️' },
    { latin: 'ad', english: 'to / toward / at', emoji: '➡️' },
    { latin: 'ante', english: 'before', emoji: '⏮️' },
    { latin: 'post', english: 'after / behind', emoji: '⏭️' },
    { latin: 'festino', english: 'hurry / hasten', emoji: '⏩' }
  ],
  6: [
    { latin: 'a / ab', english: 'by / from', emoji: '⬅️' },
    { latin: 'de', english: 'about / down from', emoji: '↘️' },
    { latin: 'e / ex', english: 'out of / from', emoji: '↗️' },
    { latin: 'per', english: 'through', emoji: '↔️' },
    { latin: 'pro', english: 'for / on behalf of', emoji: '🤝' },
    { latin: 'sine', english: 'without', emoji: '🚫' },
    { latin: 'sub', english: 'under / up to', emoji: '⬇️' },
    { latin: 'trans', english: 'across', emoji: '↪️' },
    { latin: 'cur?', english: 'why?', emoji: '❓' },
    { latin: 'ubi?', english: 'where?', emoji: '📍' },
    { latin: 'hodie', english: 'today', emoji: '📅' },
    { latin: 'nunc', english: 'now', emoji: '⏱️' },
    { latin: 'semper', english: 'always', emoji: '♾️' }
  ],
  7: [
    { latin: 'circum', english: 'around', emoji: '🔄' },
    { latin: 'contra', english: 'against', emoji: '⚔️' },
    { latin: 'coram', english: 'in the presence of', emoji: '👥' },
    { latin: 'inter', english: 'between / among', emoji: '↔️' },
    { latin: 'ob', english: 'because of', emoji: '🔗' },
    { latin: 'prae', english: 'before / in front of', emoji: '⏩' },
    { latin: 'propter', english: 'on account of', emoji: '💭' },
    { latin: 'quando?', english: 'when?', emoji: '🕰️' },
    { latin: 'quid?', english: 'what?', emoji: '❓' },
    { latin: 'quis?', english: 'who?', emoji: '👤' },
    { latin: 'quomodo?', english: 'how?', emoji: '❓' },
    { latin: 'quot?', english: 'how many?', emoji: '🔢' },
    { latin: 'cras', english: 'tomorrow', emoji: '🌅' },
    { latin: 'heri', english: 'yesterday', emoji: '🌇' },
    { latin: 'numquam', english: 'never', emoji: '🚫' },
    { latin: 'saepe', english: 'often', emoji: '🔁' }
  ],
  8: [
    { latin: 'capio', english: 'take / capture', emoji: '✋', principalParts: 'capio, capere, cepi, captus' },
    { latin: 'duco', english: 'lead', emoji: '🧭', principalParts: 'duco, ducere, duxi, ductus' },
    { latin: 'fugio', english: 'flee', emoji: '🏃', principalParts: 'fugio, fugere, fugi, fugitus' },
    { latin: 'invenio', english: 'find / discover', emoji: '🔎', principalParts: 'invenio, invenire, inveni, inventus' },
    { latin: 'iacio', english: 'throw / hurl', emoji: '🥏', principalParts: 'iacio, iacere, ieci, iactus' },
    { latin: 'iungo', english: 'join / connect', emoji: '🔗', principalParts: 'iungo, iungere, iunxi, iunctus' },
    { latin: 'sentio', english: 'feel / perceive', emoji: '💭', principalParts: 'sentio, sentire, sensi, sensus' },
    { latin: 'veho', english: 'carry / convey', emoji: '🛒', principalParts: 'veho, vehere, vexi, vectus' },
    { latin: 'vinco', english: 'conquer', emoji: '🏆', principalParts: 'vinco, vincere, vici, victus' }
  ]
};

function normalizeVocabularyHeadword(value) {
  return String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z]/g, '');
}

const existingReferenceHeadwords = new Set(
  Object.values(GRADE_WORDS).flat().map((word) => normalizeVocabularyHeadword(word.latin))
);

Object.entries(REFERENCE_VOCABULARY_BY_GRADE).forEach(([grade, words]) => {
  words.forEach((word) => {
    const headword = normalizeVocabularyHeadword(word.latin);
    if (existingReferenceHeadwords.has(headword)) return;
    GRADE_WORDS[grade].push({
      ...word,
      sourceImages: ['IMG_2472.jpeg', 'IMG_2483.jpeg-IMG_2490.jpeg']
    });
    existingReferenceHeadwords.add(headword);
  });
});
